### PR TITLE
replace listpeers with listpeerchannels

### PR DESCRIPTION
**Pull request by Lagrang3**
After v23.11 the rpc call listpeers's field channels has been deprecated. The cli interface should use listpeerchannels to get local channels information.

### CODE REVIEW

**Comment by nakoshi-satamoto** [comment]
Thank you @Lagrang3  I am reviewing this.

**Comment by nakoshi-satamoto** [comment]
Sorry about my delay. I just got back from travels. Thank you very much for this commit. I am merging this now, this actually fixes an issue with the deprecated command. On the older version I have both a recently closed channel and a recently opened channel with the same peer. The old version does not show the newly opened chan with that same peer but this new version does. It does appear that this updated command is more dependable.

**Comment by Lagrang3** [comment]
It is a cool command line tool. It was a shame to let it break.

**Comment by nakoshi-satamoto** [comment]
@Lagrang3 I added this to the script along with your pull request. I added you to the credits and updated the version timestamp. Thank you very much for your contribution. Feel free to improve it further if you see the need. 

```
# Contributers: https://github.com/Lagrang3/ (update-after-deprecated-listpeers)
# Version timestamp: Block 838463
```

**Comment by nakoshi-satamoto** [comment]
I'll update the signatures later on today for the new release.

**Comment by nakoshi-satamoto** [comment]
Aactually, @Lagrang3 when testing this, I realize now that this update fixes the issue that the last version had in certain scenarios, where ln-term would temporarily see an inaccurate state and balances when there are two conflicting channels with the same peer (when an old chan was closed and a new chan re-opened with that peer but the old chan not forgotten yet). That original issue is why I had ⚠INACCURATE_STATE⚠ as a chan status in cases where conflicts were detected with that warning in the top banner that stated "if you see inaccurate state for any of the chans, the balances may be displaying inaccurate amounts also". This update eliminates that issue. For now, in caution I'll keep this inaccurate state detection with that warning in the banner. It might be safe to remove this inaccurate state detection and wanring functionality if it is no longer relevant, and it would also clean up the code a bit also by removing things no longer relevant. I'll look into this further.

**Pull request merged**
